### PR TITLE
Add dislike support

### PR DESCRIPTION
**Pull request by themalkolm**
:)

### CODE REVIEW

**Comment by themalkolm** [comment]
Like/dislike compete whenever they are both checked though.

**Comment by austencm** [comment]
Hey, nice work!
I'm hesitant to merge this, just because I'm not sure in what situation it would be useful. What made you want to add it?

**Comment by themalkolm** [comment]
Automating likes only is like keeping only positive reviews in apple store, google store, amazon etc. and remove negative ones. Not fair! DISLIKE POWER TO THE PEOPLE! DISLIKE! DISLIKE! DISLIKE!

**Comment by austencm** [comment]
I'm gonna give this a hard no.

**Pull request closed without merging**
