### PR TITLE
Internationalization ?

### PR DESCRIPTION
**Pull request by Taknok**
I added 3 js line to allow internationalization by adding `span` element in the dom. With an id `i18n-qwerty` it will insert the **message** specified under **qwerty** from `_locales/[navigator_leng]/messages.json`
I also provided FR and SP.

### CODE REVIEW

**Comment by austencm** [comment]
Nice, thank you! I've actually been working on an i18n module that replaces text content directly using Chrome's __MSG_strName__ syntax. I'm going to push that update, then would you mind resubmitting this with just the language files?

**Comment by Taknok** [comment]
Hum I didn't found anything about `MSG_strName` on the web ? What is it ? :)
I actually can remove the "coded" files from this PR and keep only the
language files.

Le 17 août 2017 5:40 PM, "Austen Morgan" <notifications@github.com> a
écrit :

Nice, thank you! I've actually been working on an i18n module that replaces
text content directly using Chrome's *MSG_strName* syntax. I'm going to
push that update, then would you mind resubmitting this with just the
language files?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/austencm/youtube-auto-like/pull/5#issuecomment-323213476>,
or mute the thread

**Comment by austencm** [comment]
Take a peek at the [i18n documentation](https://developer.chrome.com/extensions/i18n). In manifest.json and CSS files, Chrome will automatically replace instances of `__MSG_messagename__` with the matching message. I just wrote a string replacer that does the same for the HTML files.

If you want to just leave the language files, that would work, but I updated the EN file so they need to be matched with that.

**Comment by Taknok** [comment]
Ok I see, I didn't wanted to bother me with string search in HTML so I put span with ID, but else it's quite the same process. I'm updating the language files

**Comment by Taknok** [comment]
Everything is updated ! Now I have to merge my repo with those new changes (same fonctionnalilties in parallel but slightly different).

**Comment by austencm** [comment]
You're awesome! I'll publish this version soon.

**Pull request merged**
